name: Backend CI

on:
  push:
    branches: [ master ]
    paths: [ backend ]
  pull_request:
    branches: [ master ]
    paths: [ backend ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.19.0

      - run: npm install
        working-directory: backend/src
