name: Client CI

on:
  push:
    branches: [ master ]
    paths: [ backend, .github/workflows ]
  pull_request:
    branches: [ master ]
    paths: [ backend, .github/workflows ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.19.0

      - run: npm install
        working-directory: client/src
      
      - run: npm run build
        working-directory: client/src
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: backend-artifact
          root: client/src
          path: |
            dist/
            assets/
            index.html
          retention-days: 1
